# @name loginAutenticado
POST http://localhost:40000/login HTTP/1.1
content-type: application/json

{    
    "LoginUsuario": "teste",
    "SenhaUsuario": "teste"
}
### Seta o token
@accessToken = {{loginAutenticado.response.body.$.token}}
@username = {{loginAutenticado.response.body.$.username}}



### teste de inserção de aluno
POST http://localhost:40000/insertAluno HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "idAluno": 0,
    "titulo": "Gabriel Hideki",
    "dataNasc": "2024-03-08",
    "renda": 1000.10,
    "documento": "50000-4A",
    "removido": false
}

### teste de buscar todos os aluno
GET http://localhost:40000/getAllAluno HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    
}

### teste de buscar aluno por ID
POST http://localhost:40000/getAlunoByID HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "idaluno": 1
}



### teste de atualização de aluno
PUT http://localhost:40000/updateAluno HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "idAluno": 1,
    "titulo": "Joao vitor",
    "dataNasc": "2024-03-08",
    "renda": 5000.10,
    "documento": "552222F",
    "removido": false
}

### teste de atualização de Aluno
DELETE http://localhost:40000/deleteAluno HTTP/1.1
content-type: application/json
Authorization: Bearer {{accessToken}}

{    
    "idAluno": 2
}
